pipeline {
    agent any  
    stages {
        stage('SCM'){
            steps {
                git branch: 'main', url: 'https://github.com/Hrudaya-github/jenkins-project.git'
            }
        }
        stage('Unit Testing'){
            steps {
                sh 'mvn test'
            }
        }
        stage('Integration Testing'){
            steps {
                sh 'mvn verify -DskipUnitTests'
            }
        }
        stage('Maven Build'){
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Build & Sonarqube Analysis'){
            steps {
                withSonarQubeEnv('sonar-server'){
                  sh script: 'mvn clean package sonar:sonar'
                }
            }                
        }
        stage('Quality Gate'){
            steps {
                timeout(time: 1, unit: 'HOURS') {
                  waitForQualityGate abortPipeline: true, credentialsId:'sonar-jenkins-auth'
                }
            }
        }    
        stage('upload artifact in nexus'){
            steps {
                script {
                    def readPomVersion = readMavenPom file: 'pom.xml'
                    def nexusRepo = readPomVersion.version.endsWith("SNAPSHOT") ? "nexus-app-snapshot" : "nexus-app-release"
                    nexusArtifactUploader artifacts: 
                    [
                        [
                            artifactId: 'springboot', 
                            classifier: '', 
                            file: 'target/Uber.jar',
                             type: 'jar'
                        ]
                    ],
                    credentialsId: 'nexus-auth',
                    groupId: 'com.example',
                    nexusUrl: '44.242.165.161:8081',
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    repository: nexusRepo,
                    version: "${readPomVersion.version}"
                }
            }    
        }        
    }            
}

Sonarqube Installation
----------------------
 sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.6.1.59531.zip
 sudo unzip sonarqube-9.6.1.59531.zip
 sudo mv sonarqube-9.6.1.59531 /opt/sonarqube

 sonar-auth--squ_dad05b7d06a58a2d4d6be7f2dcca6014d10c20bd

 

 

 Nexus Installation
-------------------
 sudo wget https://download.sonatype.com/nexus/3/nexus-3.42.0-01-unix.tar.gz
 sudo tar -zxvf nexus-3.42.0-01-unix.tar.gz
 sudo mv /opt/nexus-3.42.0-01 /opt/nexus



