pipeline {
    agent any  
    stages {
        stage('SCM'){
            steps {
                git branch: 'main', url: 'https://github.com/Hrudaya-github/mega-project.git'
            }
        }
         stage('Unit Testing'){
            steps {
                sh 'mvn test'
            }
        }
        stage('Integration Testing'){
            steps {
                sh 'mvn verify -DskipUnitTests' 
            }
        }
        stage('Maven Build'){
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Code Quality Analysis & Package'){
            steps{
                script{
                   withSonarQubeEnv(credentialsId: 'sonar-api') {
                   sh 'mvn clean package sonar:sonar' 
                   } 
                }
            }
        }
        stage('Quality Gate Status'){
            steps{
                script{
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-api'
                }
            }
        } 
        stage('upload artifact in nexus'){
            steps {
                script { 
                    def readPomVersion = readMavenPom file: 'pom.xml'
                    def nexusRepo = readPomVersion.version.endsWith("SNAPSHOT") ? "demoapp-snapshot" : "demoapp-release" 
                    nexusArtifactUploader artifacts: 
                    [
                        [
                            artifactId: 'springboot',
                            classifier: '', 
                            file: 'target/Uber.jar', 
                            type: '.jar'
                        ]
                    ], 
                        credentialsId: 'nexus-authorized', 
                        groupId: 'com.example', 
                        nexusUrl: '52.3.245.223:8081', 
                        nexusVersion: 'nexus3', 
                        protocol: 'http', 
                        repository: 'nexusRepo', 
                        version: "${readPomVersion.version}"
                }
            }    
        }        
    }            
}

Sonarqube Installation
----------------------
 sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.6.1.59531.zip
 sudo unzip sonarqube-9.6.1.59531.zip
 sudo mv sonarqube-9.6.1.59531 /opt/sonarqube

 sonar-auth--squ_dad05b7d06a58a2d4d6be7f2dcca6014d10c20bd

 

 

 Nexus Installation
-------------------
 sudo wget https://download.sonatype.com/nexus/3/nexus-3.42.0-01-unix.tar.gz
 sudo tar -zxvf nexus-3.42.0-01-unix.tar.gz
 sudo mv /opt/nexus-3.42.0-01 /opt/nexus



