---
apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe
spec:
  containers:
    - name: ubuntucont 
      image: ubuntu:latest
      command:
        - /bin/bash
        - -ec
        - sleep 30; touch /tmp/ready; sleep 600; rm /tmp/ready
      readinessProbe: 
        exec:
          command:
            - cat 
            - /tmp/ready
        initialDelaySeconds: 10
        periodSeconds: 5
      
      
        