---
apiVersion: v1
kind: Pod
metadata: 
  name: new-pod
spec:
  containers:
    - name: jenkinscont
      image: jenkins
      ports:
        - containerPort: 8080
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
      