---
apiVersion: v1
kind: Pod
metadata:
  name: other-pod
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - containerPort: 3306   
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'admin@123'
    - name: httpd 
      image: httpd  
      ports:
        - containerPort: 80
