---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  minReadySeconds: 10 # by default is 0
  replicas: 3 # by default is 1
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi


Explanation:
  A Headless Service, named nginx, is used to control the network domain.
  The StatefulSet, named web, has a Spec that indicates that 3 replicas of the
  nginx container will be launched in unique Pods.
  The volumeClaimTemplates will provide stable storage using PersistentVolumes provisioned by 
  a PersistentVolume Provisioner.

  