---
- name: playbook for docker
  become: yes
  hosts: docker-host
  tasks:
    - name: stop container
      shell: docker container stop hrtcloud
    - name: remove container 
      shell: docker container rm hrtcloud
    - name: remove docker image
      shell: docker image rmi hr143heart/hrtcloud
    - name: create container 
      shell: docker container run -itd --name hrtcloud-container -p 9000:80 hr143heart/hrtcloud


  