---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-demo
  labels:
    app: daemon-exmaple
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      labels:
        app: daemon 
        version: "1.0"
    spec:
      containers:
        - name: alpinecont
          image: alpine
          args:
            - /bin/sh
            - -c
            - sleep 1d 

