---
apiVersion: v1 
kind: Service
metadata: 
  name: frontend-svc
spec:
  type: NodePort
  ports:
    - nodePort: 32556
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
