---
apiVersion: v1
kind: Pod
metadata:
  name: annotate-demo-pod
  labels:
    environment: qa 
    project: qt-ehealth
    team: qa-ops
  annotations:
    commit-id: 3190dd9e231b92f07da29e052a0fbc812ed8c999
    jira-issue: "https://jira.qualtitythought.in/issue/OP-25"
spec:
  containers:
    - name: mysqlcont
      image: mysql
      ports:
        - containerPort: 3306
          protocol: TCP