---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-multiple-volume
spec:
  containers:
    - name: alpine1cont
      image: alpine 
      args:
        - /bin/sh
        - -c
        - sleep 60s
      volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /var/log
          name: logs-volume
    - name: ubuntucont
      image: ubuntu
      args:
        - /bin/bash
        - -c
        - sleep 60s
      volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /var/log
          name: logs-volume
    - name: alpine2cont
      image: alpine 
      args:
        - /bin/sh
        - -c
        - sleep 60s
      volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /var/log
          name: logs-volume
  volumes:
    - name: data-volume
      emptyDir: {}
    - name: logs-volume
      hostPath:
        path: /var/log