---
- name: playbook for docker
  hosts: all
  become: yes
  tasks:
    - name: delete old deployment
      command: kubectl delete -f /opt/deployment.yml
    - name: delete old service
      command: kubectl delete -f /opt/service.yml
    - name: apply new deployment
      command: kubectl apply -f /opt/deployment.yml
    - name: apply new service
      command: kubectl apply -f /opt/service.yml 