---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc-new
spec: 
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1GiB
  volumeMode: Filesystem

  