# base image is ubuntu
FROM ubuntu:20.04
RUN apt install openjdk-11-jdk wget && apt update -y
RUN wget https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
CMD [ "java", "-jar", "spring-petclinic-2.4.2.jar" ]
EXPOSE 8080
