---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo-pod
  labels:
    environment: dev
    team: tech-ops
    project: qt-banking
spec:
  containers:
    - name: nginx-cont
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
        